const bootstrap = async () => {
  try {
  } catch (error) {
    console.error(`Error during app bootstrap: ${error.message}`);
  }
};

bootstrap();
